RegisterSchema once per golang package #490
capnproto/go-capnp pull request #544
Opened 2023-09-06 01:21 UTC by davidhubbard

Fixes https://github.com/capnproto/go-capnp/issues/490 by only generating one `RegisterSchema()` function per `$Go.package()`.

For example, the unit tests persistent-simple.capnp and persistent-samepkg.capnp now both have the annotation:

`$Go.package("persistent_simple");`

Their generated go code thus starts with:

`package persistent_simple`

but only one of them will include a `RegisterSchema()`.

2023-09-06 01:24 UTC, davidhubbard commented on capnpc-go/capnpc-go.go
> +	canOmitSchema      bool
This line snuck in, I need to remove it.

2023-09-06 17:18 UTC, lthibault requested changes

2023-09-06 17:32 UTC, davidhubbard commented on capnpc-go/capnpc-go.go
> +		fname, _ := reqf.Filename()
Fixed. Thanks!

2023-09-08 19:27 UTC, lthibault approved these changes

2023-09-11 13:34 UTC, merged